#IFNDEF hwdefs_asm          ; TASM-specific guard
#DEFINE hwdefs_asm  1

;; -----------------------------------------------------
;; HARDWARE EQUATES AND CONSTANTS
;; -----------------------------------------------------
LOWMEM: .EQU    0           ; 0000H-7FFFH
HIMEM:  .EQU    8000H       ; 8000H-FFFFH
ROMSIZ: .EQU    8000H       ; 32K
HIMSIZ: .EQU    8000H       ; 32K
MEMTOP: .EQU    0FFFFH      ; TOP OF RAM
ROMBEG: .EQU    LOWMEM
ROMEND: .EQU    ROMBEG + ROMSIZ

;; -----------------------------------------------------
;; -- I/O MAP FOR FIREFLY REV 1 BOARD (WDE8016)
;; -----------------------------------------------------
; CONTROL & CONFIG PORT
SYSCFG: .EQU    00H         ; SYSTEM CONFIGURATION SWITCH (OPEN = 1, CLOSED = 0)
RAMCTL: .EQU    00H         ; ANY WRITE SWITCHES LOW RAM IN PLACE OF ROM (0000H-7FFFH)

; ZILOG CTC COUNTER-TIMER CHIP
CTCBAS: .EQU    04H         ; CTC BASE ADDRESS, IOSEL1 = 0X04
CTCCH0: .EQU    CTCBAS + 0  ; CTC CHANNEL 0 CONTROL REGISTER
CTCCH1: .EQU    CTCBAS + 1  ; CTC CHANNEL 1 CONTROL REGISTER
CTCCH2: .EQU    CTCBAS + 2  ; CTC CHANNEL 2 CONTROL REGISTER
CTCCH3: .EQU    CTCBAS + 3  ; CTC CHANNEL 3 CONTROL REGISTER

; ZILOG SIO SERIAL I/O *OR* DART DUAL ASYNCHRONOUS RECEIVER/TRANSMITTER
SIOBAS: .EQU    08H         ; SIO BASE ADDRESS, IOSEL2 = 0X08
SIOAD:  .EQU    SIOBAS + 0  ; SIO CHANNEL A DATA REGISTER
SIOBD:  .EQU    SIOBAS + 1  ; SIO CHANNEL B DATA REGISTER
SIOAC:  .EQU    SIOBAS + 2  ; SIO CHANNEL A CONTROL REGISTER
SIOBC:  .EQU    SIOBAS + 3  ; SIO CHANNEL B CONTROL REGISTER

; ZILOG PIO PARALLEL INPUT/OUTPUT
PIOBAS: .EQU    0CH         ; PIO BASE ADDRESS, IOSEL3 = 0X0C
PIOAD:  .EQU    PIOBAS + 0  ; PIO PORT A DATA REGISTER
PIOBD:  .EQU    PIOBAS + 1  ; PIO PORT B DATA REGISTER
PIOAC:  .EQU    PIOBAS + 2  ; PIO PORT A CONTROL REGISTER
PIOBC:  .EQU    PIOBAS + 3  ; PIO PORT B CONTROL REGISTER

; SIMPLE DEBUG DISPLAY BOARD (TESTING ADD-ON)
DS2:    .EQU    20H         ; HP7340 PAIR DISPLAYS VALUE WRITTEN TO PORT (TYP DATA)
DS4R:   .EQU    40H         ; HP7340 PAIR DISPLAYS VALUE WRITTEN TO PORT (TYP AN ADDRESS LOW BYTE)
DS4L:   .EQU    60H         ; HP7340 PAIR DISPLAYS VALUE WRITTEN TO PORT (TYP AN ADDRESS HIGH BYTE)

;; -----------------------------------------------------
;; I/O DEVICE CONTROL CONSTANTS
;; -----------------------------------------------------
;; CTC MODE PROGRAMMING CONSTANTS
CTCEI:  .EQU    128         ; ENABLE CHANNEL INTERRUPT
CTCDI:  .EQU    0           ; DISABLE CHANNEL INTERRUPT
CTCCTR: .EQU    64          ; CHANNEL COUNTER MODE
CTCTMR: .EQU    0           ; CHANNEL TIMER MODE
CTCP25: .EQU    32          ; PRESCALER = 256
CTCP16: .EQU    0           ; PRESCALER = 16
CTCTER: .EQU    16          ; CLK/TRG TRIGGER ON RISING EDGE
CTCTEF: .EQU    0           ; CLK/TRG TRIGGER ON FALLING EDGE
CTCTTC: .EQU    8           ; TIMER MODE TRIGGER - WAIT FOR CLK
CTCTTA: .EQU    0           ; TIMER MODE TRIGGER - AUTOMATIC
CTCTC:  .EQU    4           ; TIME CONSTANT FOLLOWS
CTCNTC: .EQU    0           ; NO TIME CONSTANT FOLLOWS
CTCRST: .EQU    2           ; SOFTWARE RESET
CTCRUN: .EQU    0           ; NORMAL OPERATION
CTCCTL: .EQU    1           ; VALUE IS CONTROL WORD
CTCVEC: .EQU    0           ; VALUE IS INTERRUPT VECTOR

;; PIO MODE PROGRAMMING CONSTANTS
PMODE0:    .EQU    00001111B    ; PIO MODE 0 - OUTPUT
PMODE1:    .EQU    01001111B    ; PIO MODE 1 - INPUT
PMODE2:    .EQU    10001111B    ; PIO MODE 2 - BIDIRECTIONAL
PMODE3:    .EQU    11001111B    ; PIO MODE 3 - CONTROL

;; SIO MODE PROGRAMMING CONSTANTS



        ;; -------------------------------------------------------------
#ENDIF
